### ISSUE TITLE
Installation of VDS failed

### ISSUE THREAD

**Issue by Krukiou** [Verteego/dss-doc#2]
Hey,

I have followed your installation description with Google Cloud Platform but when I execute the "Ansible Playbook" command on the terminal, the installation fail with the followinf error message : 

TASK [Make boot disk] **********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No CA Certificates were found in CA_CERTS_PATH. For information on how to get required certificate files, please visit https://libcloud.readthedocs.org/en/latest/other/ssl-certificate-validation.html"}
	to retry, use: --limit @/Users/derkrikorian/vds/deployment/ansible/setup_gc_instance.retry

How Can i fix this problem ?
thanks for your responses

Lionel

NB : I use a Mac with MacOS Sierra

**Comment by schiesslr** [comment]
Hi @Krukiou ! We'll check this ASAP. @elmehdielbrini, can you have a look please?

**Comment by elmehdielbrini** [comment]
Hi @Krukiou, i think you need to install certifi on your machine :
```bash
pip install --upgrade certifi
```
I don't have access to a MacOS machine, so it's diffcult for me to replicate your situation, so if the above command doesn't fix the issue, your can try and take a look at the libcloud ssl [documentation](https://libcloud.readthedocs.io/en/latest/other/ssl-certificate-validation.html#ssl-certificate-validation-in-v2-0) section to see if it can get you through this issue.
at last if you couldn't get it to work, i need you to run the ansible command with a higher verbose level, by adding the ```-vvvv``` flag, and pasting the output log back here in the comment section.

Mehdi.

**Comment by Krukiou** [comment]
hey Medhi,

Thanks you for your response

I have already install certifi on the machine.
when i launch the installation, the installation is failing at the same step with the following error message : 

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected response: ({u'domain': u'global', u'message': u\"Required 'compute.regions.list' permission for 'projects/verteego-161622'\", u'reason': u'forbidden'}). Detail: Traceback (most recent call last):\n  File \"/var/folders/0g/75jvrz252p5dlvngkyfy2lq00000gn/T/ansible_jybXvy/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 105, in gcp_connect\n    project=project_id)\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 1712, in __init__\n    self.region_list = self.ex_list_regions()\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 2341, in ex_list_regions\n    response = self.connection.request(request, method='GET').object\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 120, in request\n    response = super(GCEConnection, self).request(*args, **kwargs)\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 806, in request\n    *args, **kwargs)\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/common/base.py\", line 871, in request\n    response = responseCls(**kwargs)\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/common/base.py\", line 182, in __init__\n    self.object = self.parse_body()\n  File \"/Users/derkrikorian/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 294, in parse_body\n    raise GoogleBaseError(message, self.status, code)\nGoogleBaseError: {u'domain': u'global', u'message': u\"Required 'compute.regions.list' permission for 'projects/verteego-161622'\", u'reason': u'forbidden'}\n"}
	to retry, use: --limit @/Users/derkrikorian/vds/deployment/ansible/setup_gc_instance.retry

after reading the documentation it is said that : "LIBCLOUD_SSL_USE_CERTIFI environment variable to false" Can you tell me how to do this more precisely.
and can you give me an example of "ansible command with a higher verbose level" in order i run it on my machine.

thanks you

Lionel

**Comment by Krukiou** [comment]
Hey @elmehdielbrini 
I solved the problem of the installation. It was a problem of right on the project in the google cloud console.
The installation is successfully but i have a problem : 
For the final step , I go to my Google Cloud Compute Engine console on my new created instance, 
I go to SSH -> "Ouvrir dans la fenetre du navigateur sur un port personnalisé" > I set 33330 and Ihave the following error message : "Impossible d'établir la connexion avec la MV sur le port 33330"



How can i fix this problem ?

thanks

Lionel

**Comment by elmehdielbrini** [comment]
Hi @Krukiou,
it's great that you have been able to overcome the previous issues, regarding the message you get on the console, it is the normal behaviour when you try to bind to an already used tcp port, VDS uses the port 33330 as default for the superset http server.
Once the machine is created and installed in your google cloud platform project, you need to access it via a web borwser using its public/external ip address, for instance : http://104.xxx.xx.55:33330, you can find this ip address on your google cloud console page, under section compute engine as shown in the following sceenshot :
![external-ip](https://cloud.githubusercontent.com/assets/24933858/24190289/88c656d4-0ee8-11e7-9ede-6d005e8eb3ac.jpeg)

**Comment by Krukiou** [comment]
Hey Mehdi,

Thanks you for your response
I'm doing this : the new machine is created and installed in my google cloud platform project, I copy-paste the external IP adress, for me it's "104.xxx.xx.xxx" with ": 33330" , i launch the browser, but nothing happens : many seconds later, i have the following browser message : "Ce site est inaccessible

104.199.96.156 a mis trop de temps à répondre."

How can i solve this issue ?

Thanks

Lionel

**Comment by elmehdielbrini** [comment]
Hi @Krukiou,
maybe you need to add a firewall rule in your google cloud plateform project to allow the tcp port range 33330 ~> 33335, and than add it to your instance tag list :
1- Create a firewall rule with "vds" tag under (https://console.cloud.google.com/networking/firewalls/): 
![rule](https://cloud.githubusercontent.com/assets/24933858/24199761/1f659c5e-0f0b-11e7-8df3-6b158a1ec4c8.jpeg)
2- Edit the created instance settings and add the newly created firewall rule tag "vds" to Tags input (https://console.cloud.google.com/compute) :
![tag](https://cloud.githubusercontent.com/assets/24933858/24199822/58c4a95e-0f0b-11e7-9d65-e3a6b517c06c.jpeg)

**Comment by elmehdielbrini** [comment]
@Krukiou i have updated the ansible installation playbook to automatically create a firewall rule and assign its tag to the created instance, so if you still facing this issue, you can delete the instance and recreate it by replaying the ansible-playbook command, of course after pulling the latest changes from the vds github repository.

**Comment by Krukiou** [comment]
Hey Mehdi,

 By adding the firewall rule in my google cloud plateform project, i can access to the sign-in page and then to the VDS.
Problem solved.

Thanks you for your help,

Lionel

**Comment by elmehdielbrini** [comment]
Hi @Krukiou, Great :+1:
